# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application on macOS

on:
  push:
    branches: [ main ]
    paths:
      - 'main.py'
      - 'pastk/**'
      - '.github/workflows/python-app-macOS.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'main.py'
      - 'pastk/**'
      - '.github/workflows/python-app-macOS.yml'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        pip install -r requirements.txt
    - name: Package using pyinstaller
      id: package
      run: |
        pyinstaller main.py -n ${{github.event.repository.name}} -w --clean --add-data="./settings.json;." -i resources/logo/PasTk_logo.ico
    - name: Copy necessary files to the dist directory
      run: |
        cp LICENSE dist/
        cp *md dist/
#        mkdir dist/${{github.event.repository.name}}/resources
        cp -r resources/ dist/${{github.event.repository.name}}/
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.event.repository.name}}-${{runner.os}}
        path: ${{github.workspace}}/dist/
